DO $$
BEGIN
	CREATE TABLE USUARIO_SESSION (
		USUARIOSESSION_ID NUMERIC(7) NOT NULL,
		USUARIO_ID NUMERIC(7) NOT NULL,
		DEVICE_ID VARCHAR(200),
		USER_AGENT VARCHAR(200),
		PLATFORM VARCHAR(200),
		LANGUAGE VARCHAR(200),
		TOKEN_USER TEXT,
		TOKEN_ACCESS TEXT,
		DATA_MODIF TIMESTAMP,
		DATA_SESSION TIMESTAMP,
		IND_SESSION BOOLEAN,
		PRIMARY KEY (USUARIOSESSION_ID)
	);
	
	CREATE SEQUENCE USUARIOSESSION_SEQ INCREMENT BY 1 START WITH 1 NO CYCLE;
 
	EXCEPTION 
		WHEN duplicate_table THEN NULL;
	    WHEN duplicate_object THEN NULL;
	    WHEN duplicate_column THEN NULL;
END
$$;
 