DO $$
BEGIN
	CREATE TABLE PESSOA_ENDERECO (
		PESSOAENDERECO_ID NUMERIC(7) PRIMARY KEY NOT NULL,
		PESSOA_ID NUMERIC(7) NOT NULL REFERENCES PESSOA(PESSOA_ID) ON DELETE CASCADE,
		LOGRADOURO VARCHAR(255),
		NUMERO VARCHAR(10),
		COMPLEMENTO VARCHAR(255),
		BAIRRO VARCHAR(100),
		CIDADE VARCHAR(100),
		ESTADO VARCHAR(2),
		CEP VARCHAR(10)
	);
	
	CREATE SEQUENCE PESSOAENDERECO_SEQ INCREMENT BY 1 START WITH 1 NO CYCLE;
 
	EXCEPTION 
		WHEN duplicate_table THEN NULL;
	    WHEN duplicate_object THEN NULL;
	    WHEN duplicate_column THEN NULL;
END
$$;
 