DO $$
BEGIN
	CREATE TABLE PESSOA_BANCO (
		PESSOABANCO_ID NUMERIC(7) PRIMARY KEY NOT NULL,
		PESSOA_ID NUMERIC(7) NOT NULL REFERENCES PESSOA(PESSOA_ID) ON DELETE CASCADE,
		BANCO VARCHAR(100),
		AGENCIA VARCHAR(20),
		CONTA VARCHAR(20),
		TIPO_CONTA VARCHAR(20),
		TITULAR VARCHAR(255),
		CNPJ_TITULAR VARCHAR(18)
	);
	
	CREATE SEQUENCE PESSOABANCO_SEQ INCREMENT BY 1 START WITH 1 NO CYCLE;
 
	EXCEPTION 
		WHEN duplicate_table THEN NULL;
	    WHEN duplicate_object THEN NULL;
	    WHEN duplicate_column THEN NULL;
END
$$;
 