DO $$
BEGIN
	CREATE TABLE PESSOA (
		PESSOA_ID NUMERIC(7) PRIMARY KEY NOT NULL,
		TIPO_PESSOA VARCHAR(10) NOT NULL CHECK (TIPO_PESSOA IN ('FISICA', 'JURIDICA')),
		NEGOCIO_ID NUMERIC(7) NOT NULL,
		CODIGO VARCHAR(255) NOT NULL,
		NOME VARCHAR(255) NOT NULL,
		NOME_FANTASIA VARCHAR(255),
		CPF VARCHAR(30),
		CNPJ VARCHAR(30),
		INSCRICAO_ESTADUAL VARCHAR(50),
		INSCRICAO_MUNICIPAL VARCHAR(50),
		TELEFONE VARCHAR(20),
		EMAIL VARCHAR(255),
		SITE VARCHAR(255),
		RESPONSAVEL VARCHAR(255),
		TELEFONE_RESPONSAVEL VARCHAR(20),
		OBSERVACOES TEXT,
		ATIVO BOOLEAN DEFAULT TRUE,
		DATA_MODIF TIMESTAMP,
		DATA_CADASTRO TIMESTAMP
	);
	
	CREATE SEQUENCE PESSOA_SEQ INCREMENT BY 1 START WITH 1 NO CYCLE;
 
	EXCEPTION 
		WHEN duplicate_table THEN NULL;
	    WHEN duplicate_object THEN NULL;
	    WHEN duplicate_column THEN NULL;
END
$$;
 