DO $$
BEGIN
	CREATE TABLE PRODUTO (
		PRODUTO_ID NUMERIC(7) NOT NULL,
		FORNECEDOR_ID NUMERIC(7) NOT NULL,
		CODIGO VARCHAR(100),
		DESCRICAO VARCHAR(500),
		MARCA VARCHAR(200),
		UNIDADE VARCHAR(20),
		PRECO NUMERIC(7,2),
		DATA_MODIF TIMESTAMP,
		USUARIOMODIF_ID NUMERIC(7),
		PRIMARY KEY (PRODUTO_ID)
	);
	
	CREATE SEQUENCE PRODUTO_SEQ INCREMENT BY 1 START WITH 1 NO CYCLE;
 
	EXCEPTION 
		WHEN duplicate_table THEN NULL;
	    WHEN duplicate_object THEN NULL;
	    WHEN duplicate_column THEN NULL;
END
$$;