DO $$
BEGIN
	ALTER TABLE FORNECEDOR DROP COLUMN CODIGO;
	ALTER TABLE FORNECEDOR DROP COLUMN NOME;
	ALTER TABLE FORNECEDOR DROP COLUMN NOME_FANTASIA;
	ALTER TABLE FORNECEDOR DROP COLUMN CNPJ;
	ALTER TABLE FORNECEDOR DROP COLUMN ENDERECO;
	ALTER TABLE FORNECEDOR DROP COLUMN IMAGEM;
	ALTER TABLE FORNECEDOR DROP COLUMN NEGOCIO_ID;
	ALTER TABLE FORNECEDOR ADD COLUMN PESSOA_ID NUMERIC(7);
	ALTER TABLE COMPRADOR DROP COLUMN CODIGO;
	ALTER TABLE COMPRADOR DROP COLUMN NOME;
	ALTER TABLE COMPRADOR DROP COLUMN CNPJ;
	ALTER TABLE COMPRADOR DROP COLUMN ENDERECO;
	ALTER TABLE COMPRADOR DROP COLUMN IMAGEM;
	ALTER TABLE COMPRADOR DROP COLUMN NEGOCIO_ID;
	ALTER TABLE COMPRADOR ADD COLUMN PESSOA_ID NUMERIC(7);

  	EXCEPTION WHEN duplicate_column THEN NULL;
END
$$;