DO $$
BEGIN
	ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_PERFIL_FK FOREIGN KEY (PERFIL_ID) REFERENCES PERFIL (PERFIL_ID) ;
	ALTER TABLE PRODUTO ADD CONSTRAINT PRODUTO_FORNECEDOR_FK FOREIGN KEY (FORNECEDOR_ID) REFERENCES FORNECEDOR (FORNECEDOR_ID) ;	
	ALTER TABLE FORNECEDOR ADD CONSTRAINT FORNECEDOR_NEGOCIO_FK FOREIGN KEY (NEGOCIO_ID) REFERENCES NEGOCIO (NEGOCIO_ID) ;
	ALTER TABLE FORNECEDOR_USUARIO ADD CONSTRAINT FORNECEDOR_USUARIO_FK FOREIGN KEY (FORNECEDOR_ID) REFERENCES FORNECEDOR (FORNECEDOR_ID) ;
	ALTER TABLE FORNECEDOR_USUARIO ADD CONSTRAINT USUARIO_FORNECEDOR_FK FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (USUARIO_ID) ;
	ALTER TABLE PEDIDO ADD CONSTRAINT PEDIDO_USUARIO_FK FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (USUARIO_ID) ;
	ALTER TABLE PEDIDO ADD CONSTRAINT PEDIDO_COMPRADOR_FK FOREIGN KEY (COMPRADOR_ID) REFERENCES COMPRADOR (COMPRADOR_ID) ;
	ALTER TABLE PEDIDO_PRODUTO ADD CONSTRAINT PEDIDO_PRODUTO_FK FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO (PEDIDO_ID) ;
	ALTER TABLE PEDIDO_PRODUTO ADD CONSTRAINT PRODUTO_PEDIDO_FK FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO (PRODUTO_ID) ;
	ALTER TABLE PEDIDO_PRODUTO ADD CONSTRAINT PRODPED_ESTOQUE_FK FOREIGN KEY (ESTOQUE_ID) REFERENCES ESTOQUE (ESTOQUE_ID) ;
	ALTER TABLE ESTOQUE ADD CONSTRAINT ESTOQUE_USUARIO_FK FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (USUARIO_ID) ;
	ALTER TABLE ESTOQUE ADD CONSTRAINT ESTOQUE_PRODUTO_FK FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTO (PRODUTO_ID) ;
	ALTER TABLE COMPRADOR ADD CONSTRAINT COMPRADOR_NEGOCIO_FK FOREIGN KEY (NEGOCIO_ID) REFERENCES NEGOCIO (NEGOCIO_ID) ;
	ALTER TABLE COMPRADOR_USUARIO ADD CONSTRAINT COMPRADOR_USUARIO_FK FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO (USUARIO_ID) ;
	ALTER TABLE COMPRADOR_USUARIO ADD CONSTRAINT USUARIO_COMPRADOR_FK FOREIGN KEY (COMPRADOR_ID) REFERENCES COMPRADOR (COMPRADOR_ID) ;
  	EXCEPTION WHEN duplicate_column THEN NULL;
END
$$;